---
title: "VIS_Assignment4"
author: "Julia Meinhardt"
date: "10/3/2020"
output: 
  html_document:
        toc: true
        toc_float: true
        code_folding: hide 
---

```{r setup, message=FALSE}

library(osmdata)
library(opentripplanner)
library(tidyverse)
library(sf)
library(ggthemes)
library(ggspatial)
```
### Description



```{r, loading kml}

bzm_boulders <- st_read("https://opendata.arcgis.com/datasets/1931fd26d0cf4f0caee3173911ee9b5d_2.kml?outSR=%7B%22latestWkid%22%3A26912%2C%22wkid%22%3A26912%7D")
  
```
```{r}
opq(bbox = 'Bozeman MT USA') %>%
  add_osm_feature(key = 'highway') %>%
  osmdata_xml(file = 'OTP/graphs/default/bozeman_streets.osm')
```

```{r}
MT_projection <- "+proj=lcc +lat_1=49 +lat_2=45 +lat_0=44.25 +lon_0=-109.5 +x_0=599999.9999976 +y_0=0 +ellps=GRS80 +datum=NAD83 +to_meter=0.3048 +no_defs "


bozeman_street_features <- opq(bbox = 'Bozeman MT USA') %>%
  add_osm_feature(key = 'highway') %>%
  osmdata_sf()

bozeman_streets <- bozeman_street_features$osm_lines %>%
  st_transform(crs = MT_projection)
```

```{r}
ggplot(bozeman_streets) +
  geom_sf() +
  theme_map()
```

```{r, message=FALSE}
path_data <- file.path(getwd(), "OTP")
path_otp <- paste(path_data, "otp.jar",sep = "/")

otp_build_graph(otp = path_otp, dir = path_data, memory = 1024) 
```


```{r}
otp_setup(otp = path_otp, dir = path_data, memory =1024)
```

```{r}
otpcon <- otp_connect()
```
```{r}
iso_5min_walk <- 
  otp_isochrone(otpcon = otpcon, fromPlace = bzm_boulders, 
                mode = "WALK", cutoffSec = 300) %>%

iso_5min_drive <- 
  otp_isochrone(otpcon = otpcon, fromPlace = bzm_boulders, 
                mode = "CAR", cutoffSec = 300) %>%

iso_all_modes <- rbind(iso_5min_drive, iso_5min_walk)


```
```{r}
otp_stop()
```

