---
title: 'Assignment 7: Raster Interpolation'
author: "Julia Meinhardt"
date: "11/1/2020"
output: html_document
---

```{r, include=FALSE}
library(tidycensus)
library(tidyverse)
library(sf)
library(dplyr)
library(tidyr)
options(tigris_use_cache = TRUE)
library(raster)
library(gstat)
library(spatial)
```

```{r}
area_vars_2018 <- load_variables(2018, "acs1")
```


```{r}
county_vars <- get_acs(state = "CA", geography= "county", variables = "B25035_001", geometry = TRUE) 
```

Median Year Structure Was Built

```{r cloropleth}
county_vars %>%
  ggplot(aes(fill = estimate)) +
  geom_sf(color = NA) +
  coord_sf(crs = 4687) +
  scale_fill_viridis_c(option = "magma") +
  
  theme_minimal()
```

```{r}

WGS84 <-  "+proj=lcc +lat_1=41.66666666666666 +lat_2=40 +lat_0=39.33333333333334 +lon_0=-122 +x_0=2000000.0001016 +y_0=500000.0001016001 +ellps=GRS80 +datum=NAD83 +to_meter=0.3048006096012192 +no_defs "
NAD83 <- "+proj=aea +lat_1=34 +lat_2=40.5 +lat_0=0 +lon_0=-120 +x_0=0 +y_0=-4000000 +ellps=GRS80 +datum=NAD83 +units=m +no_defs "


```

```{r}
county_points <- st_centroid(
  st_transform(county_vars, crs = NAD83))

```


```{r}
  ggplot(county_points, aes()) +
  geom_sf(data = county_vars)+
  geom_sf(data = county_points, pch = 1, color = "red") +
  coord_sf(crs = 4687) +
  scale_fill_viridis_c(option = "magma") +
  
  theme_minimal()
```




```{r}
counties_points <- county_points %>%
  st_transform(WGS84) %>%
  as_Spatial()

counties_poly <- county_vars %>%
  st_transform(WGS84) %>%
  as_Spatial()
  
  
```

  
```{r}
counties_raster <- raster(counties_poly, res=20)
```


```{r}
test <- gstat(formula=estimate~1, locations=counties_points)

``` 

```{r}
interpol <- interpolate(final_raster, test)
```
```{r}
interpol_clip<- mask(interpol, counties_poly)
```

```{r}
ggplot() +
  geom_raster(data = interpol_clip,
              aes(x = x, y = y)) + 

  coord_quickmap()
```



